name: git-github-docs-env

channels:
  - https://metoffice.jfrog.io/metoffice/api/conda/conda-forge
  - nodefaults

dependencies:
  - pre-commit
  - sphinx-rtd-theme
  - sphinx
  - sphinx-autobuild
  - sphinx-copybutton
  - sphinx-design
  - sphinxcontrib-mermaid
