name: ProFSea-env
channels:
  - conda-agnostic
  - conda-main
  - conda-mo-internal
  - conda-forge
dependencies:
  - numpy
  - pandas
  - python=3.7.7
  - scipy
  - pyyaml
  - netcdf4
  - matplotlib
  - libwebp>=1.3.2