[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "profsea"
version = "3.0"
dependencies = ["numpy", "xarray", "scipy", "dask"]

[tool.setuptools.packages.find]
include = ["profsea*"]
exclude = ["docs*", "tests*"]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-cov",  # Useful for checking test coverage later
]
