# Site(s) information
# region: region of the world
#   N.B. used to create output folder structure
# sitename: tide gauge name or other site name
#   N.B. if site_name has an apostrophe use triple quotes
#       # sitename: '''site'x'''
# sitelatlon: site location's latitude and longitude
#   N.B. if tide gauge name: latlon taken from TG metadata
        # sitelatlon: [[]])
#   N.B. if other site name: latlon needs to be specified
        # sitelatlon: [[-51.69, -57.82]])
siteinfo:
    region: 'Falkland_example'   # str
    sitename: ['Andene', 'Barentsburg', 'Dunai (Dunai Ostrov)', 'Polyarniy', 'Prudhoe Bay,  Alaska', 'Qikiqtarjuaq', 'Reykjavik', 'Tuktoyaktuk', 'Vankarem', 'Vise (Vise Ostrov)']     # list
    sitelatlon: [[]]             # list 

# Base output directory
#   N.B. the code will add region to the output directory
baseoutdir: '/data/users/gmunday/slr/sl_output/'

# Science method
#   UKCP18 --> sciencemethod: 'UK'
#   Palmer et al (2020) --> sciencemethod: 'global
#       N.B. Used to identify which GIA estimates to use
sciencemethod: 'global'  # str

# Tide gauge information (recommend default below)
# source: source of tide gauge information
#   N.B. Also used to identify which TG directory to use
# datafq: temporal scale of tide gauge data
#   N.B. not set up monthly files for PSMSL
# psmsldir: TG base directory
tidegaugeinfo:
    source: 'PSMSL'    # str
    datafq: ['annual'] # list
    psmsldir: '/home/h04/gmunday/Documents/ukcr/ProFSea-tool/data/'

# CMIP information
cmipinfo:
# cmip_sea: for non-UK locations, specify if site is within marginal sea
#   Not in a marginal sea --> cmip_sea: 'all'
#   Marginal sea --> cmip_sea: 'marginal'
    cmip_sea: 'all'     # str
# sealevelbasedir: Base directory for CMIP "zos" and "zostoga" data
    sealevelbasedir: '/project/ukcp18/sealeveltool/'
# slopecoeffsuk: CMIP5 slope coefficients developed for UKCP18
    slopecoeffsuk: /project/ukcp18/sealeveltool/'


# Directories for the GIA estimates (independent of scenario)
#   UKCP18 --> UK specific ones
#   Global locations --> Lambeck, ICE5G
giaestimates:
    global: '/project/ukcp18/sealeveltool/global_GIA_interpolators.pickle'
    uk: '/project/ukcp18/sealeveltool/Bradley_GIA_interpolator.pickle'

# Directories for the Slangen, Spada and Klemann fingerprints
fingerprints:
    slangendir: '/project/ukcp18/sealeveltool/'
    spadadir: '/project/ukcp18/sealeveltool/'
    klemanndir: '/project/ukcp18/sealeveltool/'

# Directory of Monte Carlo time series for new projections
#   N.B. Originally developed by Jonathan Gregory
montecarlodir: '/project/ukcp18/sealeveltool/'
